# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/a18573961/.brew/Cellar/cmake/3.17.3/bin/cmake

# The command to remove a file.
RM = /Users/a18573961/.brew/Cellar/cmake/3.17.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/a18573961/Desktop/code/Minishell/libft

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/a18573961/Desktop/code/Minishell/libft

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/a18573961/.brew/Cellar/cmake/3.17.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/a18573961/.brew/Cellar/cmake/3.17.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/a18573961/Desktop/code/Minishell/libft/CMakeFiles /Users/a18573961/Desktop/code/Minishell/libft/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/a18573961/Desktop/code/Minishell/libft/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ft

# Build rule for target.
ft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ft
.PHONY : ft

# fast build rule for target.
ft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/build
.PHONY : ft/fast

source/error/char_error.o: source/error/char_error.c.o

.PHONY : source/error/char_error.o

# target to build an object file
source/error/char_error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/error/char_error.c.o
.PHONY : source/error/char_error.c.o

source/error/char_error.i: source/error/char_error.c.i

.PHONY : source/error/char_error.i

# target to preprocess a source file
source/error/char_error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/error/char_error.c.i
.PHONY : source/error/char_error.c.i

source/error/char_error.s: source/error/char_error.c.s

.PHONY : source/error/char_error.s

# target to generate assembly for a file
source/error/char_error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/error/char_error.c.s
.PHONY : source/error/char_error.c.s

source/error/ft_exit.o: source/error/ft_exit.c.o

.PHONY : source/error/ft_exit.o

# target to build an object file
source/error/ft_exit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/error/ft_exit.c.o
.PHONY : source/error/ft_exit.c.o

source/error/ft_exit.i: source/error/ft_exit.c.i

.PHONY : source/error/ft_exit.i

# target to preprocess a source file
source/error/ft_exit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/error/ft_exit.c.i
.PHONY : source/error/ft_exit.c.i

source/error/ft_exit.s: source/error/ft_exit.c.s

.PHONY : source/error/ft_exit.s

# target to generate assembly for a file
source/error/ft_exit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/error/ft_exit.c.s
.PHONY : source/error/ft_exit.c.s

source/error/int_error.o: source/error/int_error.c.o

.PHONY : source/error/int_error.o

# target to build an object file
source/error/int_error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/error/int_error.c.o
.PHONY : source/error/int_error.c.o

source/error/int_error.i: source/error/int_error.c.i

.PHONY : source/error/int_error.i

# target to preprocess a source file
source/error/int_error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/error/int_error.c.i
.PHONY : source/error/int_error.c.i

source/error/int_error.s: source/error/int_error.c.s

.PHONY : source/error/int_error.s

# target to generate assembly for a file
source/error/int_error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/error/int_error.c.s
.PHONY : source/error/int_error.c.s

source/error/void_error.o: source/error/void_error.c.o

.PHONY : source/error/void_error.o

# target to build an object file
source/error/void_error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/error/void_error.c.o
.PHONY : source/error/void_error.c.o

source/error/void_error.i: source/error/void_error.c.i

.PHONY : source/error/void_error.i

# target to preprocess a source file
source/error/void_error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/error/void_error.c.i
.PHONY : source/error/void_error.c.i

source/error/void_error.s: source/error/void_error.c.s

.PHONY : source/error/void_error.s

# target to generate assembly for a file
source/error/void_error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/error/void_error.c.s
.PHONY : source/error/void_error.c.s

source/io/ft_putchar.o: source/io/ft_putchar.c.o

.PHONY : source/io/ft_putchar.o

# target to build an object file
source/io/ft_putchar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putchar.c.o
.PHONY : source/io/ft_putchar.c.o

source/io/ft_putchar.i: source/io/ft_putchar.c.i

.PHONY : source/io/ft_putchar.i

# target to preprocess a source file
source/io/ft_putchar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putchar.c.i
.PHONY : source/io/ft_putchar.c.i

source/io/ft_putchar.s: source/io/ft_putchar.c.s

.PHONY : source/io/ft_putchar.s

# target to generate assembly for a file
source/io/ft_putchar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putchar.c.s
.PHONY : source/io/ft_putchar.c.s

source/io/ft_putchar_fd.o: source/io/ft_putchar_fd.c.o

.PHONY : source/io/ft_putchar_fd.o

# target to build an object file
source/io/ft_putchar_fd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putchar_fd.c.o
.PHONY : source/io/ft_putchar_fd.c.o

source/io/ft_putchar_fd.i: source/io/ft_putchar_fd.c.i

.PHONY : source/io/ft_putchar_fd.i

# target to preprocess a source file
source/io/ft_putchar_fd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putchar_fd.c.i
.PHONY : source/io/ft_putchar_fd.c.i

source/io/ft_putchar_fd.s: source/io/ft_putchar_fd.c.s

.PHONY : source/io/ft_putchar_fd.s

# target to generate assembly for a file
source/io/ft_putchar_fd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putchar_fd.c.s
.PHONY : source/io/ft_putchar_fd.c.s

source/io/ft_putendl.o: source/io/ft_putendl.c.o

.PHONY : source/io/ft_putendl.o

# target to build an object file
source/io/ft_putendl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putendl.c.o
.PHONY : source/io/ft_putendl.c.o

source/io/ft_putendl.i: source/io/ft_putendl.c.i

.PHONY : source/io/ft_putendl.i

# target to preprocess a source file
source/io/ft_putendl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putendl.c.i
.PHONY : source/io/ft_putendl.c.i

source/io/ft_putendl.s: source/io/ft_putendl.c.s

.PHONY : source/io/ft_putendl.s

# target to generate assembly for a file
source/io/ft_putendl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putendl.c.s
.PHONY : source/io/ft_putendl.c.s

source/io/ft_putendl_fd.o: source/io/ft_putendl_fd.c.o

.PHONY : source/io/ft_putendl_fd.o

# target to build an object file
source/io/ft_putendl_fd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putendl_fd.c.o
.PHONY : source/io/ft_putendl_fd.c.o

source/io/ft_putendl_fd.i: source/io/ft_putendl_fd.c.i

.PHONY : source/io/ft_putendl_fd.i

# target to preprocess a source file
source/io/ft_putendl_fd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putendl_fd.c.i
.PHONY : source/io/ft_putendl_fd.c.i

source/io/ft_putendl_fd.s: source/io/ft_putendl_fd.c.s

.PHONY : source/io/ft_putendl_fd.s

# target to generate assembly for a file
source/io/ft_putendl_fd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putendl_fd.c.s
.PHONY : source/io/ft_putendl_fd.c.s

source/io/ft_putnbr.o: source/io/ft_putnbr.c.o

.PHONY : source/io/ft_putnbr.o

# target to build an object file
source/io/ft_putnbr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putnbr.c.o
.PHONY : source/io/ft_putnbr.c.o

source/io/ft_putnbr.i: source/io/ft_putnbr.c.i

.PHONY : source/io/ft_putnbr.i

# target to preprocess a source file
source/io/ft_putnbr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putnbr.c.i
.PHONY : source/io/ft_putnbr.c.i

source/io/ft_putnbr.s: source/io/ft_putnbr.c.s

.PHONY : source/io/ft_putnbr.s

# target to generate assembly for a file
source/io/ft_putnbr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putnbr.c.s
.PHONY : source/io/ft_putnbr.c.s

source/io/ft_putnbr_fd.o: source/io/ft_putnbr_fd.c.o

.PHONY : source/io/ft_putnbr_fd.o

# target to build an object file
source/io/ft_putnbr_fd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putnbr_fd.c.o
.PHONY : source/io/ft_putnbr_fd.c.o

source/io/ft_putnbr_fd.i: source/io/ft_putnbr_fd.c.i

.PHONY : source/io/ft_putnbr_fd.i

# target to preprocess a source file
source/io/ft_putnbr_fd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putnbr_fd.c.i
.PHONY : source/io/ft_putnbr_fd.c.i

source/io/ft_putnbr_fd.s: source/io/ft_putnbr_fd.c.s

.PHONY : source/io/ft_putnbr_fd.s

# target to generate assembly for a file
source/io/ft_putnbr_fd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putnbr_fd.c.s
.PHONY : source/io/ft_putnbr_fd.c.s

source/io/ft_putstr.o: source/io/ft_putstr.c.o

.PHONY : source/io/ft_putstr.o

# target to build an object file
source/io/ft_putstr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putstr.c.o
.PHONY : source/io/ft_putstr.c.o

source/io/ft_putstr.i: source/io/ft_putstr.c.i

.PHONY : source/io/ft_putstr.i

# target to preprocess a source file
source/io/ft_putstr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putstr.c.i
.PHONY : source/io/ft_putstr.c.i

source/io/ft_putstr.s: source/io/ft_putstr.c.s

.PHONY : source/io/ft_putstr.s

# target to generate assembly for a file
source/io/ft_putstr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putstr.c.s
.PHONY : source/io/ft_putstr.c.s

source/io/ft_putstr_fd.o: source/io/ft_putstr_fd.c.o

.PHONY : source/io/ft_putstr_fd.o

# target to build an object file
source/io/ft_putstr_fd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putstr_fd.c.o
.PHONY : source/io/ft_putstr_fd.c.o

source/io/ft_putstr_fd.i: source/io/ft_putstr_fd.c.i

.PHONY : source/io/ft_putstr_fd.i

# target to preprocess a source file
source/io/ft_putstr_fd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putstr_fd.c.i
.PHONY : source/io/ft_putstr_fd.c.i

source/io/ft_putstr_fd.s: source/io/ft_putstr_fd.c.s

.PHONY : source/io/ft_putstr_fd.s

# target to generate assembly for a file
source/io/ft_putstr_fd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/ft_putstr_fd.c.s
.PHONY : source/io/ft_putstr_fd.c.s

source/io/print_arr_str.o: source/io/print_arr_str.c.o

.PHONY : source/io/print_arr_str.o

# target to build an object file
source/io/print_arr_str.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/print_arr_str.c.o
.PHONY : source/io/print_arr_str.c.o

source/io/print_arr_str.i: source/io/print_arr_str.c.i

.PHONY : source/io/print_arr_str.i

# target to preprocess a source file
source/io/print_arr_str.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/print_arr_str.c.i
.PHONY : source/io/print_arr_str.c.i

source/io/print_arr_str.s: source/io/print_arr_str.c.s

.PHONY : source/io/print_arr_str.s

# target to generate assembly for a file
source/io/print_arr_str.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/print_arr_str.c.s
.PHONY : source/io/print_arr_str.c.s

source/io/putchar_color.o: source/io/putchar_color.c.o

.PHONY : source/io/putchar_color.o

# target to build an object file
source/io/putchar_color.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/putchar_color.c.o
.PHONY : source/io/putchar_color.c.o

source/io/putchar_color.i: source/io/putchar_color.c.i

.PHONY : source/io/putchar_color.i

# target to preprocess a source file
source/io/putchar_color.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/putchar_color.c.i
.PHONY : source/io/putchar_color.c.i

source/io/putchar_color.s: source/io/putchar_color.c.s

.PHONY : source/io/putchar_color.s

# target to generate assembly for a file
source/io/putchar_color.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/putchar_color.c.s
.PHONY : source/io/putchar_color.c.s

source/io/putstr_color.o: source/io/putstr_color.c.o

.PHONY : source/io/putstr_color.o

# target to build an object file
source/io/putstr_color.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/putstr_color.c.o
.PHONY : source/io/putstr_color.c.o

source/io/putstr_color.i: source/io/putstr_color.c.i

.PHONY : source/io/putstr_color.i

# target to preprocess a source file
source/io/putstr_color.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/putstr_color.c.i
.PHONY : source/io/putstr_color.c.i

source/io/putstr_color.s: source/io/putstr_color.c.s

.PHONY : source/io/putstr_color.s

# target to generate assembly for a file
source/io/putstr_color.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/io/putstr_color.c.s
.PHONY : source/io/putstr_color.c.s

source/memory/ft_bzero.o: source/memory/ft_bzero.c.o

.PHONY : source/memory/ft_bzero.o

# target to build an object file
source/memory/ft_bzero.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_bzero.c.o
.PHONY : source/memory/ft_bzero.c.o

source/memory/ft_bzero.i: source/memory/ft_bzero.c.i

.PHONY : source/memory/ft_bzero.i

# target to preprocess a source file
source/memory/ft_bzero.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_bzero.c.i
.PHONY : source/memory/ft_bzero.c.i

source/memory/ft_bzero.s: source/memory/ft_bzero.c.s

.PHONY : source/memory/ft_bzero.s

# target to generate assembly for a file
source/memory/ft_bzero.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_bzero.c.s
.PHONY : source/memory/ft_bzero.c.s

source/memory/ft_destroy_int_arr.o: source/memory/ft_destroy_int_arr.c.o

.PHONY : source/memory/ft_destroy_int_arr.o

# target to build an object file
source/memory/ft_destroy_int_arr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_destroy_int_arr.c.o
.PHONY : source/memory/ft_destroy_int_arr.c.o

source/memory/ft_destroy_int_arr.i: source/memory/ft_destroy_int_arr.c.i

.PHONY : source/memory/ft_destroy_int_arr.i

# target to preprocess a source file
source/memory/ft_destroy_int_arr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_destroy_int_arr.c.i
.PHONY : source/memory/ft_destroy_int_arr.c.i

source/memory/ft_destroy_int_arr.s: source/memory/ft_destroy_int_arr.c.s

.PHONY : source/memory/ft_destroy_int_arr.s

# target to generate assembly for a file
source/memory/ft_destroy_int_arr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_destroy_int_arr.c.s
.PHONY : source/memory/ft_destroy_int_arr.c.s

source/memory/ft_destroy_string_arr.o: source/memory/ft_destroy_string_arr.c.o

.PHONY : source/memory/ft_destroy_string_arr.o

# target to build an object file
source/memory/ft_destroy_string_arr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_destroy_string_arr.c.o
.PHONY : source/memory/ft_destroy_string_arr.c.o

source/memory/ft_destroy_string_arr.i: source/memory/ft_destroy_string_arr.c.i

.PHONY : source/memory/ft_destroy_string_arr.i

# target to preprocess a source file
source/memory/ft_destroy_string_arr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_destroy_string_arr.c.i
.PHONY : source/memory/ft_destroy_string_arr.c.i

source/memory/ft_destroy_string_arr.s: source/memory/ft_destroy_string_arr.c.s

.PHONY : source/memory/ft_destroy_string_arr.s

# target to generate assembly for a file
source/memory/ft_destroy_string_arr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_destroy_string_arr.c.s
.PHONY : source/memory/ft_destroy_string_arr.c.s

source/memory/ft_memalloc.o: source/memory/ft_memalloc.c.o

.PHONY : source/memory/ft_memalloc.o

# target to build an object file
source/memory/ft_memalloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memalloc.c.o
.PHONY : source/memory/ft_memalloc.c.o

source/memory/ft_memalloc.i: source/memory/ft_memalloc.c.i

.PHONY : source/memory/ft_memalloc.i

# target to preprocess a source file
source/memory/ft_memalloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memalloc.c.i
.PHONY : source/memory/ft_memalloc.c.i

source/memory/ft_memalloc.s: source/memory/ft_memalloc.c.s

.PHONY : source/memory/ft_memalloc.s

# target to generate assembly for a file
source/memory/ft_memalloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memalloc.c.s
.PHONY : source/memory/ft_memalloc.c.s

source/memory/ft_memccpy.o: source/memory/ft_memccpy.c.o

.PHONY : source/memory/ft_memccpy.o

# target to build an object file
source/memory/ft_memccpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memccpy.c.o
.PHONY : source/memory/ft_memccpy.c.o

source/memory/ft_memccpy.i: source/memory/ft_memccpy.c.i

.PHONY : source/memory/ft_memccpy.i

# target to preprocess a source file
source/memory/ft_memccpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memccpy.c.i
.PHONY : source/memory/ft_memccpy.c.i

source/memory/ft_memccpy.s: source/memory/ft_memccpy.c.s

.PHONY : source/memory/ft_memccpy.s

# target to generate assembly for a file
source/memory/ft_memccpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memccpy.c.s
.PHONY : source/memory/ft_memccpy.c.s

source/memory/ft_memchr.o: source/memory/ft_memchr.c.o

.PHONY : source/memory/ft_memchr.o

# target to build an object file
source/memory/ft_memchr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memchr.c.o
.PHONY : source/memory/ft_memchr.c.o

source/memory/ft_memchr.i: source/memory/ft_memchr.c.i

.PHONY : source/memory/ft_memchr.i

# target to preprocess a source file
source/memory/ft_memchr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memchr.c.i
.PHONY : source/memory/ft_memchr.c.i

source/memory/ft_memchr.s: source/memory/ft_memchr.c.s

.PHONY : source/memory/ft_memchr.s

# target to generate assembly for a file
source/memory/ft_memchr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memchr.c.s
.PHONY : source/memory/ft_memchr.c.s

source/memory/ft_memcmp.o: source/memory/ft_memcmp.c.o

.PHONY : source/memory/ft_memcmp.o

# target to build an object file
source/memory/ft_memcmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memcmp.c.o
.PHONY : source/memory/ft_memcmp.c.o

source/memory/ft_memcmp.i: source/memory/ft_memcmp.c.i

.PHONY : source/memory/ft_memcmp.i

# target to preprocess a source file
source/memory/ft_memcmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memcmp.c.i
.PHONY : source/memory/ft_memcmp.c.i

source/memory/ft_memcmp.s: source/memory/ft_memcmp.c.s

.PHONY : source/memory/ft_memcmp.s

# target to generate assembly for a file
source/memory/ft_memcmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memcmp.c.s
.PHONY : source/memory/ft_memcmp.c.s

source/memory/ft_memcpy.o: source/memory/ft_memcpy.c.o

.PHONY : source/memory/ft_memcpy.o

# target to build an object file
source/memory/ft_memcpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memcpy.c.o
.PHONY : source/memory/ft_memcpy.c.o

source/memory/ft_memcpy.i: source/memory/ft_memcpy.c.i

.PHONY : source/memory/ft_memcpy.i

# target to preprocess a source file
source/memory/ft_memcpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memcpy.c.i
.PHONY : source/memory/ft_memcpy.c.i

source/memory/ft_memcpy.s: source/memory/ft_memcpy.c.s

.PHONY : source/memory/ft_memcpy.s

# target to generate assembly for a file
source/memory/ft_memcpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memcpy.c.s
.PHONY : source/memory/ft_memcpy.c.s

source/memory/ft_memdel.o: source/memory/ft_memdel.c.o

.PHONY : source/memory/ft_memdel.o

# target to build an object file
source/memory/ft_memdel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memdel.c.o
.PHONY : source/memory/ft_memdel.c.o

source/memory/ft_memdel.i: source/memory/ft_memdel.c.i

.PHONY : source/memory/ft_memdel.i

# target to preprocess a source file
source/memory/ft_memdel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memdel.c.i
.PHONY : source/memory/ft_memdel.c.i

source/memory/ft_memdel.s: source/memory/ft_memdel.c.s

.PHONY : source/memory/ft_memdel.s

# target to generate assembly for a file
source/memory/ft_memdel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memdel.c.s
.PHONY : source/memory/ft_memdel.c.s

source/memory/ft_memmove.o: source/memory/ft_memmove.c.o

.PHONY : source/memory/ft_memmove.o

# target to build an object file
source/memory/ft_memmove.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memmove.c.o
.PHONY : source/memory/ft_memmove.c.o

source/memory/ft_memmove.i: source/memory/ft_memmove.c.i

.PHONY : source/memory/ft_memmove.i

# target to preprocess a source file
source/memory/ft_memmove.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memmove.c.i
.PHONY : source/memory/ft_memmove.c.i

source/memory/ft_memmove.s: source/memory/ft_memmove.c.s

.PHONY : source/memory/ft_memmove.s

# target to generate assembly for a file
source/memory/ft_memmove.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memmove.c.s
.PHONY : source/memory/ft_memmove.c.s

source/memory/ft_memset.o: source/memory/ft_memset.c.o

.PHONY : source/memory/ft_memset.o

# target to build an object file
source/memory/ft_memset.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memset.c.o
.PHONY : source/memory/ft_memset.c.o

source/memory/ft_memset.i: source/memory/ft_memset.c.i

.PHONY : source/memory/ft_memset.i

# target to preprocess a source file
source/memory/ft_memset.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memset.c.i
.PHONY : source/memory/ft_memset.c.i

source/memory/ft_memset.s: source/memory/ft_memset.c.s

.PHONY : source/memory/ft_memset.s

# target to generate assembly for a file
source/memory/ft_memset.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_memset.c.s
.PHONY : source/memory/ft_memset.c.s

source/memory/ft_realloc.o: source/memory/ft_realloc.c.o

.PHONY : source/memory/ft_realloc.o

# target to build an object file
source/memory/ft_realloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_realloc.c.o
.PHONY : source/memory/ft_realloc.c.o

source/memory/ft_realloc.i: source/memory/ft_realloc.c.i

.PHONY : source/memory/ft_realloc.i

# target to preprocess a source file
source/memory/ft_realloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_realloc.c.i
.PHONY : source/memory/ft_realloc.c.i

source/memory/ft_realloc.s: source/memory/ft_realloc.c.s

.PHONY : source/memory/ft_realloc.s

# target to generate assembly for a file
source/memory/ft_realloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_realloc.c.s
.PHONY : source/memory/ft_realloc.c.s

source/memory/ft_safe_malloc.o: source/memory/ft_safe_malloc.c.o

.PHONY : source/memory/ft_safe_malloc.o

# target to build an object file
source/memory/ft_safe_malloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_safe_malloc.c.o
.PHONY : source/memory/ft_safe_malloc.c.o

source/memory/ft_safe_malloc.i: source/memory/ft_safe_malloc.c.i

.PHONY : source/memory/ft_safe_malloc.i

# target to preprocess a source file
source/memory/ft_safe_malloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_safe_malloc.c.i
.PHONY : source/memory/ft_safe_malloc.c.i

source/memory/ft_safe_malloc.s: source/memory/ft_safe_malloc.c.s

.PHONY : source/memory/ft_safe_malloc.s

# target to generate assembly for a file
source/memory/ft_safe_malloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/memory/ft_safe_malloc.c.s
.PHONY : source/memory/ft_safe_malloc.c.s

source/sort/my_bubble_sort.o: source/sort/my_bubble_sort.c.o

.PHONY : source/sort/my_bubble_sort.o

# target to build an object file
source/sort/my_bubble_sort.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/sort/my_bubble_sort.c.o
.PHONY : source/sort/my_bubble_sort.c.o

source/sort/my_bubble_sort.i: source/sort/my_bubble_sort.c.i

.PHONY : source/sort/my_bubble_sort.i

# target to preprocess a source file
source/sort/my_bubble_sort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/sort/my_bubble_sort.c.i
.PHONY : source/sort/my_bubble_sort.c.i

source/sort/my_bubble_sort.s: source/sort/my_bubble_sort.c.s

.PHONY : source/sort/my_bubble_sort.s

# target to generate assembly for a file
source/sort/my_bubble_sort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/sort/my_bubble_sort.c.s
.PHONY : source/sort/my_bubble_sort.c.s

source/sort/my_quick_sort.o: source/sort/my_quick_sort.c.o

.PHONY : source/sort/my_quick_sort.o

# target to build an object file
source/sort/my_quick_sort.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/sort/my_quick_sort.c.o
.PHONY : source/sort/my_quick_sort.c.o

source/sort/my_quick_sort.i: source/sort/my_quick_sort.c.i

.PHONY : source/sort/my_quick_sort.i

# target to preprocess a source file
source/sort/my_quick_sort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/sort/my_quick_sort.c.i
.PHONY : source/sort/my_quick_sort.c.i

source/sort/my_quick_sort.s: source/sort/my_quick_sort.c.s

.PHONY : source/sort/my_quick_sort.s

# target to generate assembly for a file
source/sort/my_quick_sort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/sort/my_quick_sort.c.s
.PHONY : source/sort/my_quick_sort.c.s

source/string/ft_atof.o: source/string/ft_atof.c.o

.PHONY : source/string/ft_atof.o

# target to build an object file
source/string/ft_atof.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_atof.c.o
.PHONY : source/string/ft_atof.c.o

source/string/ft_atof.i: source/string/ft_atof.c.i

.PHONY : source/string/ft_atof.i

# target to preprocess a source file
source/string/ft_atof.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_atof.c.i
.PHONY : source/string/ft_atof.c.i

source/string/ft_atof.s: source/string/ft_atof.c.s

.PHONY : source/string/ft_atof.s

# target to generate assembly for a file
source/string/ft_atof.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_atof.c.s
.PHONY : source/string/ft_atof.c.s

source/string/ft_atoi.o: source/string/ft_atoi.c.o

.PHONY : source/string/ft_atoi.o

# target to build an object file
source/string/ft_atoi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_atoi.c.o
.PHONY : source/string/ft_atoi.c.o

source/string/ft_atoi.i: source/string/ft_atoi.c.i

.PHONY : source/string/ft_atoi.i

# target to preprocess a source file
source/string/ft_atoi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_atoi.c.i
.PHONY : source/string/ft_atoi.c.i

source/string/ft_atoi.s: source/string/ft_atoi.c.s

.PHONY : source/string/ft_atoi.s

# target to generate assembly for a file
source/string/ft_atoi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_atoi.c.s
.PHONY : source/string/ft_atoi.c.s

source/string/ft_atoi_base.o: source/string/ft_atoi_base.c.o

.PHONY : source/string/ft_atoi_base.o

# target to build an object file
source/string/ft_atoi_base.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_atoi_base.c.o
.PHONY : source/string/ft_atoi_base.c.o

source/string/ft_atoi_base.i: source/string/ft_atoi_base.c.i

.PHONY : source/string/ft_atoi_base.i

# target to preprocess a source file
source/string/ft_atoi_base.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_atoi_base.c.i
.PHONY : source/string/ft_atoi_base.c.i

source/string/ft_atoi_base.s: source/string/ft_atoi_base.c.s

.PHONY : source/string/ft_atoi_base.s

# target to generate assembly for a file
source/string/ft_atoi_base.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_atoi_base.c.s
.PHONY : source/string/ft_atoi_base.c.s

source/string/ft_find_symb_in_str_arr.o: source/string/ft_find_symb_in_str_arr.c.o

.PHONY : source/string/ft_find_symb_in_str_arr.o

# target to build an object file
source/string/ft_find_symb_in_str_arr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_find_symb_in_str_arr.c.o
.PHONY : source/string/ft_find_symb_in_str_arr.c.o

source/string/ft_find_symb_in_str_arr.i: source/string/ft_find_symb_in_str_arr.c.i

.PHONY : source/string/ft_find_symb_in_str_arr.i

# target to preprocess a source file
source/string/ft_find_symb_in_str_arr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_find_symb_in_str_arr.c.i
.PHONY : source/string/ft_find_symb_in_str_arr.c.i

source/string/ft_find_symb_in_str_arr.s: source/string/ft_find_symb_in_str_arr.c.s

.PHONY : source/string/ft_find_symb_in_str_arr.s

# target to generate assembly for a file
source/string/ft_find_symb_in_str_arr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_find_symb_in_str_arr.c.s
.PHONY : source/string/ft_find_symb_in_str_arr.c.s

source/string/ft_getnbr.o: source/string/ft_getnbr.c.o

.PHONY : source/string/ft_getnbr.o

# target to build an object file
source/string/ft_getnbr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_getnbr.c.o
.PHONY : source/string/ft_getnbr.c.o

source/string/ft_getnbr.i: source/string/ft_getnbr.c.i

.PHONY : source/string/ft_getnbr.i

# target to preprocess a source file
source/string/ft_getnbr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_getnbr.c.i
.PHONY : source/string/ft_getnbr.c.i

source/string/ft_getnbr.s: source/string/ft_getnbr.c.s

.PHONY : source/string/ft_getnbr.s

# target to generate assembly for a file
source/string/ft_getnbr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_getnbr.c.s
.PHONY : source/string/ft_getnbr.c.s

source/string/ft_isalnum.o: source/string/ft_isalnum.c.o

.PHONY : source/string/ft_isalnum.o

# target to build an object file
source/string/ft_isalnum.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isalnum.c.o
.PHONY : source/string/ft_isalnum.c.o

source/string/ft_isalnum.i: source/string/ft_isalnum.c.i

.PHONY : source/string/ft_isalnum.i

# target to preprocess a source file
source/string/ft_isalnum.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isalnum.c.i
.PHONY : source/string/ft_isalnum.c.i

source/string/ft_isalnum.s: source/string/ft_isalnum.c.s

.PHONY : source/string/ft_isalnum.s

# target to generate assembly for a file
source/string/ft_isalnum.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isalnum.c.s
.PHONY : source/string/ft_isalnum.c.s

source/string/ft_isalpha.o: source/string/ft_isalpha.c.o

.PHONY : source/string/ft_isalpha.o

# target to build an object file
source/string/ft_isalpha.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isalpha.c.o
.PHONY : source/string/ft_isalpha.c.o

source/string/ft_isalpha.i: source/string/ft_isalpha.c.i

.PHONY : source/string/ft_isalpha.i

# target to preprocess a source file
source/string/ft_isalpha.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isalpha.c.i
.PHONY : source/string/ft_isalpha.c.i

source/string/ft_isalpha.s: source/string/ft_isalpha.c.s

.PHONY : source/string/ft_isalpha.s

# target to generate assembly for a file
source/string/ft_isalpha.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isalpha.c.s
.PHONY : source/string/ft_isalpha.c.s

source/string/ft_isascii.o: source/string/ft_isascii.c.o

.PHONY : source/string/ft_isascii.o

# target to build an object file
source/string/ft_isascii.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isascii.c.o
.PHONY : source/string/ft_isascii.c.o

source/string/ft_isascii.i: source/string/ft_isascii.c.i

.PHONY : source/string/ft_isascii.i

# target to preprocess a source file
source/string/ft_isascii.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isascii.c.i
.PHONY : source/string/ft_isascii.c.i

source/string/ft_isascii.s: source/string/ft_isascii.c.s

.PHONY : source/string/ft_isascii.s

# target to generate assembly for a file
source/string/ft_isascii.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isascii.c.s
.PHONY : source/string/ft_isascii.c.s

source/string/ft_isdigit.o: source/string/ft_isdigit.c.o

.PHONY : source/string/ft_isdigit.o

# target to build an object file
source/string/ft_isdigit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isdigit.c.o
.PHONY : source/string/ft_isdigit.c.o

source/string/ft_isdigit.i: source/string/ft_isdigit.c.i

.PHONY : source/string/ft_isdigit.i

# target to preprocess a source file
source/string/ft_isdigit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isdigit.c.i
.PHONY : source/string/ft_isdigit.c.i

source/string/ft_isdigit.s: source/string/ft_isdigit.c.s

.PHONY : source/string/ft_isdigit.s

# target to generate assembly for a file
source/string/ft_isdigit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isdigit.c.s
.PHONY : source/string/ft_isdigit.c.s

source/string/ft_isnumber.o: source/string/ft_isnumber.c.o

.PHONY : source/string/ft_isnumber.o

# target to build an object file
source/string/ft_isnumber.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isnumber.c.o
.PHONY : source/string/ft_isnumber.c.o

source/string/ft_isnumber.i: source/string/ft_isnumber.c.i

.PHONY : source/string/ft_isnumber.i

# target to preprocess a source file
source/string/ft_isnumber.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isnumber.c.i
.PHONY : source/string/ft_isnumber.c.i

source/string/ft_isnumber.s: source/string/ft_isnumber.c.s

.PHONY : source/string/ft_isnumber.s

# target to generate assembly for a file
source/string/ft_isnumber.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isnumber.c.s
.PHONY : source/string/ft_isnumber.c.s

source/string/ft_isprint.o: source/string/ft_isprint.c.o

.PHONY : source/string/ft_isprint.o

# target to build an object file
source/string/ft_isprint.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isprint.c.o
.PHONY : source/string/ft_isprint.c.o

source/string/ft_isprint.i: source/string/ft_isprint.c.i

.PHONY : source/string/ft_isprint.i

# target to preprocess a source file
source/string/ft_isprint.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isprint.c.i
.PHONY : source/string/ft_isprint.c.i

source/string/ft_isprint.s: source/string/ft_isprint.c.s

.PHONY : source/string/ft_isprint.s

# target to generate assembly for a file
source/string/ft_isprint.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_isprint.c.s
.PHONY : source/string/ft_isprint.c.s

source/string/ft_itoa.o: source/string/ft_itoa.c.o

.PHONY : source/string/ft_itoa.o

# target to build an object file
source/string/ft_itoa.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_itoa.c.o
.PHONY : source/string/ft_itoa.c.o

source/string/ft_itoa.i: source/string/ft_itoa.c.i

.PHONY : source/string/ft_itoa.i

# target to preprocess a source file
source/string/ft_itoa.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_itoa.c.i
.PHONY : source/string/ft_itoa.c.i

source/string/ft_itoa.s: source/string/ft_itoa.c.s

.PHONY : source/string/ft_itoa.s

# target to generate assembly for a file
source/string/ft_itoa.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_itoa.c.s
.PHONY : source/string/ft_itoa.c.s

source/string/ft_len_arr.o: source/string/ft_len_arr.c.o

.PHONY : source/string/ft_len_arr.o

# target to build an object file
source/string/ft_len_arr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_len_arr.c.o
.PHONY : source/string/ft_len_arr.c.o

source/string/ft_len_arr.i: source/string/ft_len_arr.c.i

.PHONY : source/string/ft_len_arr.i

# target to preprocess a source file
source/string/ft_len_arr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_len_arr.c.i
.PHONY : source/string/ft_len_arr.c.i

source/string/ft_len_arr.s: source/string/ft_len_arr.c.s

.PHONY : source/string/ft_len_arr.s

# target to generate assembly for a file
source/string/ft_len_arr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_len_arr.c.s
.PHONY : source/string/ft_len_arr.c.s

source/string/ft_strcat.o: source/string/ft_strcat.c.o

.PHONY : source/string/ft_strcat.o

# target to build an object file
source/string/ft_strcat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strcat.c.o
.PHONY : source/string/ft_strcat.c.o

source/string/ft_strcat.i: source/string/ft_strcat.c.i

.PHONY : source/string/ft_strcat.i

# target to preprocess a source file
source/string/ft_strcat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strcat.c.i
.PHONY : source/string/ft_strcat.c.i

source/string/ft_strcat.s: source/string/ft_strcat.c.s

.PHONY : source/string/ft_strcat.s

# target to generate assembly for a file
source/string/ft_strcat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strcat.c.s
.PHONY : source/string/ft_strcat.c.s

source/string/ft_strchr.o: source/string/ft_strchr.c.o

.PHONY : source/string/ft_strchr.o

# target to build an object file
source/string/ft_strchr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strchr.c.o
.PHONY : source/string/ft_strchr.c.o

source/string/ft_strchr.i: source/string/ft_strchr.c.i

.PHONY : source/string/ft_strchr.i

# target to preprocess a source file
source/string/ft_strchr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strchr.c.i
.PHONY : source/string/ft_strchr.c.i

source/string/ft_strchr.s: source/string/ft_strchr.c.s

.PHONY : source/string/ft_strchr.s

# target to generate assembly for a file
source/string/ft_strchr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strchr.c.s
.PHONY : source/string/ft_strchr.c.s

source/string/ft_strchrdup.o: source/string/ft_strchrdup.c.o

.PHONY : source/string/ft_strchrdup.o

# target to build an object file
source/string/ft_strchrdup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strchrdup.c.o
.PHONY : source/string/ft_strchrdup.c.o

source/string/ft_strchrdup.i: source/string/ft_strchrdup.c.i

.PHONY : source/string/ft_strchrdup.i

# target to preprocess a source file
source/string/ft_strchrdup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strchrdup.c.i
.PHONY : source/string/ft_strchrdup.c.i

source/string/ft_strchrdup.s: source/string/ft_strchrdup.c.s

.PHONY : source/string/ft_strchrdup.s

# target to generate assembly for a file
source/string/ft_strchrdup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strchrdup.c.s
.PHONY : source/string/ft_strchrdup.c.s

source/string/ft_strcmp.o: source/string/ft_strcmp.c.o

.PHONY : source/string/ft_strcmp.o

# target to build an object file
source/string/ft_strcmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strcmp.c.o
.PHONY : source/string/ft_strcmp.c.o

source/string/ft_strcmp.i: source/string/ft_strcmp.c.i

.PHONY : source/string/ft_strcmp.i

# target to preprocess a source file
source/string/ft_strcmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strcmp.c.i
.PHONY : source/string/ft_strcmp.c.i

source/string/ft_strcmp.s: source/string/ft_strcmp.c.s

.PHONY : source/string/ft_strcmp.s

# target to generate assembly for a file
source/string/ft_strcmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strcmp.c.s
.PHONY : source/string/ft_strcmp.c.s

source/string/ft_strcpy.o: source/string/ft_strcpy.c.o

.PHONY : source/string/ft_strcpy.o

# target to build an object file
source/string/ft_strcpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strcpy.c.o
.PHONY : source/string/ft_strcpy.c.o

source/string/ft_strcpy.i: source/string/ft_strcpy.c.i

.PHONY : source/string/ft_strcpy.i

# target to preprocess a source file
source/string/ft_strcpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strcpy.c.i
.PHONY : source/string/ft_strcpy.c.i

source/string/ft_strcpy.s: source/string/ft_strcpy.c.s

.PHONY : source/string/ft_strcpy.s

# target to generate assembly for a file
source/string/ft_strcpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strcpy.c.s
.PHONY : source/string/ft_strcpy.c.s

source/string/ft_strdel.o: source/string/ft_strdel.c.o

.PHONY : source/string/ft_strdel.o

# target to build an object file
source/string/ft_strdel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strdel.c.o
.PHONY : source/string/ft_strdel.c.o

source/string/ft_strdel.i: source/string/ft_strdel.c.i

.PHONY : source/string/ft_strdel.i

# target to preprocess a source file
source/string/ft_strdel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strdel.c.i
.PHONY : source/string/ft_strdel.c.i

source/string/ft_strdel.s: source/string/ft_strdel.c.s

.PHONY : source/string/ft_strdel.s

# target to generate assembly for a file
source/string/ft_strdel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strdel.c.s
.PHONY : source/string/ft_strdel.c.s

source/string/ft_strdup.o: source/string/ft_strdup.c.o

.PHONY : source/string/ft_strdup.o

# target to build an object file
source/string/ft_strdup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strdup.c.o
.PHONY : source/string/ft_strdup.c.o

source/string/ft_strdup.i: source/string/ft_strdup.c.i

.PHONY : source/string/ft_strdup.i

# target to preprocess a source file
source/string/ft_strdup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strdup.c.i
.PHONY : source/string/ft_strdup.c.i

source/string/ft_strdup.s: source/string/ft_strdup.c.s

.PHONY : source/string/ft_strdup.s

# target to generate assembly for a file
source/string/ft_strdup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strdup.c.s
.PHONY : source/string/ft_strdup.c.s

source/string/ft_strequ.o: source/string/ft_strequ.c.o

.PHONY : source/string/ft_strequ.o

# target to build an object file
source/string/ft_strequ.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strequ.c.o
.PHONY : source/string/ft_strequ.c.o

source/string/ft_strequ.i: source/string/ft_strequ.c.i

.PHONY : source/string/ft_strequ.i

# target to preprocess a source file
source/string/ft_strequ.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strequ.c.i
.PHONY : source/string/ft_strequ.c.i

source/string/ft_strequ.s: source/string/ft_strequ.c.s

.PHONY : source/string/ft_strequ.s

# target to generate assembly for a file
source/string/ft_strequ.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strequ.c.s
.PHONY : source/string/ft_strequ.c.s

source/string/ft_striter.o: source/string/ft_striter.c.o

.PHONY : source/string/ft_striter.o

# target to build an object file
source/string/ft_striter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_striter.c.o
.PHONY : source/string/ft_striter.c.o

source/string/ft_striter.i: source/string/ft_striter.c.i

.PHONY : source/string/ft_striter.i

# target to preprocess a source file
source/string/ft_striter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_striter.c.i
.PHONY : source/string/ft_striter.c.i

source/string/ft_striter.s: source/string/ft_striter.c.s

.PHONY : source/string/ft_striter.s

# target to generate assembly for a file
source/string/ft_striter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_striter.c.s
.PHONY : source/string/ft_striter.c.s

source/string/ft_striteri.o: source/string/ft_striteri.c.o

.PHONY : source/string/ft_striteri.o

# target to build an object file
source/string/ft_striteri.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_striteri.c.o
.PHONY : source/string/ft_striteri.c.o

source/string/ft_striteri.i: source/string/ft_striteri.c.i

.PHONY : source/string/ft_striteri.i

# target to preprocess a source file
source/string/ft_striteri.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_striteri.c.i
.PHONY : source/string/ft_striteri.c.i

source/string/ft_striteri.s: source/string/ft_striteri.c.s

.PHONY : source/string/ft_striteri.s

# target to generate assembly for a file
source/string/ft_striteri.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_striteri.c.s
.PHONY : source/string/ft_striteri.c.s

source/string/ft_strjoin.o: source/string/ft_strjoin.c.o

.PHONY : source/string/ft_strjoin.o

# target to build an object file
source/string/ft_strjoin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strjoin.c.o
.PHONY : source/string/ft_strjoin.c.o

source/string/ft_strjoin.i: source/string/ft_strjoin.c.i

.PHONY : source/string/ft_strjoin.i

# target to preprocess a source file
source/string/ft_strjoin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strjoin.c.i
.PHONY : source/string/ft_strjoin.c.i

source/string/ft_strjoin.s: source/string/ft_strjoin.c.s

.PHONY : source/string/ft_strjoin.s

# target to generate assembly for a file
source/string/ft_strjoin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strjoin.c.s
.PHONY : source/string/ft_strjoin.c.s

source/string/ft_strjoin_free.o: source/string/ft_strjoin_free.c.o

.PHONY : source/string/ft_strjoin_free.o

# target to build an object file
source/string/ft_strjoin_free.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strjoin_free.c.o
.PHONY : source/string/ft_strjoin_free.c.o

source/string/ft_strjoin_free.i: source/string/ft_strjoin_free.c.i

.PHONY : source/string/ft_strjoin_free.i

# target to preprocess a source file
source/string/ft_strjoin_free.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strjoin_free.c.i
.PHONY : source/string/ft_strjoin_free.c.i

source/string/ft_strjoin_free.s: source/string/ft_strjoin_free.c.s

.PHONY : source/string/ft_strjoin_free.s

# target to generate assembly for a file
source/string/ft_strjoin_free.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strjoin_free.c.s
.PHONY : source/string/ft_strjoin_free.c.s

source/string/ft_strlcat.o: source/string/ft_strlcat.c.o

.PHONY : source/string/ft_strlcat.o

# target to build an object file
source/string/ft_strlcat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strlcat.c.o
.PHONY : source/string/ft_strlcat.c.o

source/string/ft_strlcat.i: source/string/ft_strlcat.c.i

.PHONY : source/string/ft_strlcat.i

# target to preprocess a source file
source/string/ft_strlcat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strlcat.c.i
.PHONY : source/string/ft_strlcat.c.i

source/string/ft_strlcat.s: source/string/ft_strlcat.c.s

.PHONY : source/string/ft_strlcat.s

# target to generate assembly for a file
source/string/ft_strlcat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strlcat.c.s
.PHONY : source/string/ft_strlcat.c.s

source/string/ft_strlen.o: source/string/ft_strlen.c.o

.PHONY : source/string/ft_strlen.o

# target to build an object file
source/string/ft_strlen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strlen.c.o
.PHONY : source/string/ft_strlen.c.o

source/string/ft_strlen.i: source/string/ft_strlen.c.i

.PHONY : source/string/ft_strlen.i

# target to preprocess a source file
source/string/ft_strlen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strlen.c.i
.PHONY : source/string/ft_strlen.c.i

source/string/ft_strlen.s: source/string/ft_strlen.c.s

.PHONY : source/string/ft_strlen.s

# target to generate assembly for a file
source/string/ft_strlen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strlen.c.s
.PHONY : source/string/ft_strlen.c.s

source/string/ft_strlow.o: source/string/ft_strlow.c.o

.PHONY : source/string/ft_strlow.o

# target to build an object file
source/string/ft_strlow.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strlow.c.o
.PHONY : source/string/ft_strlow.c.o

source/string/ft_strlow.i: source/string/ft_strlow.c.i

.PHONY : source/string/ft_strlow.i

# target to preprocess a source file
source/string/ft_strlow.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strlow.c.i
.PHONY : source/string/ft_strlow.c.i

source/string/ft_strlow.s: source/string/ft_strlow.c.s

.PHONY : source/string/ft_strlow.s

# target to generate assembly for a file
source/string/ft_strlow.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strlow.c.s
.PHONY : source/string/ft_strlow.c.s

source/string/ft_strmap.o: source/string/ft_strmap.c.o

.PHONY : source/string/ft_strmap.o

# target to build an object file
source/string/ft_strmap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strmap.c.o
.PHONY : source/string/ft_strmap.c.o

source/string/ft_strmap.i: source/string/ft_strmap.c.i

.PHONY : source/string/ft_strmap.i

# target to preprocess a source file
source/string/ft_strmap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strmap.c.i
.PHONY : source/string/ft_strmap.c.i

source/string/ft_strmap.s: source/string/ft_strmap.c.s

.PHONY : source/string/ft_strmap.s

# target to generate assembly for a file
source/string/ft_strmap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strmap.c.s
.PHONY : source/string/ft_strmap.c.s

source/string/ft_strmapi.o: source/string/ft_strmapi.c.o

.PHONY : source/string/ft_strmapi.o

# target to build an object file
source/string/ft_strmapi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strmapi.c.o
.PHONY : source/string/ft_strmapi.c.o

source/string/ft_strmapi.i: source/string/ft_strmapi.c.i

.PHONY : source/string/ft_strmapi.i

# target to preprocess a source file
source/string/ft_strmapi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strmapi.c.i
.PHONY : source/string/ft_strmapi.c.i

source/string/ft_strmapi.s: source/string/ft_strmapi.c.s

.PHONY : source/string/ft_strmapi.s

# target to generate assembly for a file
source/string/ft_strmapi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strmapi.c.s
.PHONY : source/string/ft_strmapi.c.s

source/string/ft_strncat.o: source/string/ft_strncat.c.o

.PHONY : source/string/ft_strncat.o

# target to build an object file
source/string/ft_strncat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strncat.c.o
.PHONY : source/string/ft_strncat.c.o

source/string/ft_strncat.i: source/string/ft_strncat.c.i

.PHONY : source/string/ft_strncat.i

# target to preprocess a source file
source/string/ft_strncat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strncat.c.i
.PHONY : source/string/ft_strncat.c.i

source/string/ft_strncat.s: source/string/ft_strncat.c.s

.PHONY : source/string/ft_strncat.s

# target to generate assembly for a file
source/string/ft_strncat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strncat.c.s
.PHONY : source/string/ft_strncat.c.s

source/string/ft_strncmp.o: source/string/ft_strncmp.c.o

.PHONY : source/string/ft_strncmp.o

# target to build an object file
source/string/ft_strncmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strncmp.c.o
.PHONY : source/string/ft_strncmp.c.o

source/string/ft_strncmp.i: source/string/ft_strncmp.c.i

.PHONY : source/string/ft_strncmp.i

# target to preprocess a source file
source/string/ft_strncmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strncmp.c.i
.PHONY : source/string/ft_strncmp.c.i

source/string/ft_strncmp.s: source/string/ft_strncmp.c.s

.PHONY : source/string/ft_strncmp.s

# target to generate assembly for a file
source/string/ft_strncmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strncmp.c.s
.PHONY : source/string/ft_strncmp.c.s

source/string/ft_strncpy.o: source/string/ft_strncpy.c.o

.PHONY : source/string/ft_strncpy.o

# target to build an object file
source/string/ft_strncpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strncpy.c.o
.PHONY : source/string/ft_strncpy.c.o

source/string/ft_strncpy.i: source/string/ft_strncpy.c.i

.PHONY : source/string/ft_strncpy.i

# target to preprocess a source file
source/string/ft_strncpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strncpy.c.i
.PHONY : source/string/ft_strncpy.c.i

source/string/ft_strncpy.s: source/string/ft_strncpy.c.s

.PHONY : source/string/ft_strncpy.s

# target to generate assembly for a file
source/string/ft_strncpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strncpy.c.s
.PHONY : source/string/ft_strncpy.c.s

source/string/ft_strnequ.o: source/string/ft_strnequ.c.o

.PHONY : source/string/ft_strnequ.o

# target to build an object file
source/string/ft_strnequ.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strnequ.c.o
.PHONY : source/string/ft_strnequ.c.o

source/string/ft_strnequ.i: source/string/ft_strnequ.c.i

.PHONY : source/string/ft_strnequ.i

# target to preprocess a source file
source/string/ft_strnequ.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strnequ.c.i
.PHONY : source/string/ft_strnequ.c.i

source/string/ft_strnequ.s: source/string/ft_strnequ.c.s

.PHONY : source/string/ft_strnequ.s

# target to generate assembly for a file
source/string/ft_strnequ.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strnequ.c.s
.PHONY : source/string/ft_strnequ.c.s

source/string/ft_strnew.o: source/string/ft_strnew.c.o

.PHONY : source/string/ft_strnew.o

# target to build an object file
source/string/ft_strnew.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strnew.c.o
.PHONY : source/string/ft_strnew.c.o

source/string/ft_strnew.i: source/string/ft_strnew.c.i

.PHONY : source/string/ft_strnew.i

# target to preprocess a source file
source/string/ft_strnew.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strnew.c.i
.PHONY : source/string/ft_strnew.c.i

source/string/ft_strnew.s: source/string/ft_strnew.c.s

.PHONY : source/string/ft_strnew.s

# target to generate assembly for a file
source/string/ft_strnew.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strnew.c.s
.PHONY : source/string/ft_strnew.c.s

source/string/ft_strnstr.o: source/string/ft_strnstr.c.o

.PHONY : source/string/ft_strnstr.o

# target to build an object file
source/string/ft_strnstr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strnstr.c.o
.PHONY : source/string/ft_strnstr.c.o

source/string/ft_strnstr.i: source/string/ft_strnstr.c.i

.PHONY : source/string/ft_strnstr.i

# target to preprocess a source file
source/string/ft_strnstr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strnstr.c.i
.PHONY : source/string/ft_strnstr.c.i

source/string/ft_strnstr.s: source/string/ft_strnstr.c.s

.PHONY : source/string/ft_strnstr.s

# target to generate assembly for a file
source/string/ft_strnstr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strnstr.c.s
.PHONY : source/string/ft_strnstr.c.s

source/string/ft_strrchr.o: source/string/ft_strrchr.c.o

.PHONY : source/string/ft_strrchr.o

# target to build an object file
source/string/ft_strrchr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strrchr.c.o
.PHONY : source/string/ft_strrchr.c.o

source/string/ft_strrchr.i: source/string/ft_strrchr.c.i

.PHONY : source/string/ft_strrchr.i

# target to preprocess a source file
source/string/ft_strrchr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strrchr.c.i
.PHONY : source/string/ft_strrchr.c.i

source/string/ft_strrchr.s: source/string/ft_strrchr.c.s

.PHONY : source/string/ft_strrchr.s

# target to generate assembly for a file
source/string/ft_strrchr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strrchr.c.s
.PHONY : source/string/ft_strrchr.c.s

source/string/ft_strrev.o: source/string/ft_strrev.c.o

.PHONY : source/string/ft_strrev.o

# target to build an object file
source/string/ft_strrev.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strrev.c.o
.PHONY : source/string/ft_strrev.c.o

source/string/ft_strrev.i: source/string/ft_strrev.c.i

.PHONY : source/string/ft_strrev.i

# target to preprocess a source file
source/string/ft_strrev.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strrev.c.i
.PHONY : source/string/ft_strrev.c.i

source/string/ft_strrev.s: source/string/ft_strrev.c.s

.PHONY : source/string/ft_strrev.s

# target to generate assembly for a file
source/string/ft_strrev.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strrev.c.s
.PHONY : source/string/ft_strrev.c.s

source/string/ft_strsplit.o: source/string/ft_strsplit.c.o

.PHONY : source/string/ft_strsplit.o

# target to build an object file
source/string/ft_strsplit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strsplit.c.o
.PHONY : source/string/ft_strsplit.c.o

source/string/ft_strsplit.i: source/string/ft_strsplit.c.i

.PHONY : source/string/ft_strsplit.i

# target to preprocess a source file
source/string/ft_strsplit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strsplit.c.i
.PHONY : source/string/ft_strsplit.c.i

source/string/ft_strsplit.s: source/string/ft_strsplit.c.s

.PHONY : source/string/ft_strsplit.s

# target to generate assembly for a file
source/string/ft_strsplit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strsplit.c.s
.PHONY : source/string/ft_strsplit.c.s

source/string/ft_strstr.o: source/string/ft_strstr.c.o

.PHONY : source/string/ft_strstr.o

# target to build an object file
source/string/ft_strstr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strstr.c.o
.PHONY : source/string/ft_strstr.c.o

source/string/ft_strstr.i: source/string/ft_strstr.c.i

.PHONY : source/string/ft_strstr.i

# target to preprocess a source file
source/string/ft_strstr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strstr.c.i
.PHONY : source/string/ft_strstr.c.i

source/string/ft_strstr.s: source/string/ft_strstr.c.s

.PHONY : source/string/ft_strstr.s

# target to generate assembly for a file
source/string/ft_strstr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strstr.c.s
.PHONY : source/string/ft_strstr.c.s

source/string/ft_strsub.o: source/string/ft_strsub.c.o

.PHONY : source/string/ft_strsub.o

# target to build an object file
source/string/ft_strsub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strsub.c.o
.PHONY : source/string/ft_strsub.c.o

source/string/ft_strsub.i: source/string/ft_strsub.c.i

.PHONY : source/string/ft_strsub.i

# target to preprocess a source file
source/string/ft_strsub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strsub.c.i
.PHONY : source/string/ft_strsub.c.i

source/string/ft_strsub.s: source/string/ft_strsub.c.s

.PHONY : source/string/ft_strsub.s

# target to generate assembly for a file
source/string/ft_strsub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strsub.c.s
.PHONY : source/string/ft_strsub.c.s

source/string/ft_strtrim.o: source/string/ft_strtrim.c.o

.PHONY : source/string/ft_strtrim.o

# target to build an object file
source/string/ft_strtrim.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strtrim.c.o
.PHONY : source/string/ft_strtrim.c.o

source/string/ft_strtrim.i: source/string/ft_strtrim.c.i

.PHONY : source/string/ft_strtrim.i

# target to preprocess a source file
source/string/ft_strtrim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strtrim.c.i
.PHONY : source/string/ft_strtrim.c.i

source/string/ft_strtrim.s: source/string/ft_strtrim.c.s

.PHONY : source/string/ft_strtrim.s

# target to generate assembly for a file
source/string/ft_strtrim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strtrim.c.s
.PHONY : source/string/ft_strtrim.c.s

source/string/ft_strup.o: source/string/ft_strup.c.o

.PHONY : source/string/ft_strup.o

# target to build an object file
source/string/ft_strup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strup.c.o
.PHONY : source/string/ft_strup.c.o

source/string/ft_strup.i: source/string/ft_strup.c.i

.PHONY : source/string/ft_strup.i

# target to preprocess a source file
source/string/ft_strup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strup.c.i
.PHONY : source/string/ft_strup.c.i

source/string/ft_strup.s: source/string/ft_strup.c.s

.PHONY : source/string/ft_strup.s

# target to generate assembly for a file
source/string/ft_strup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_strup.c.s
.PHONY : source/string/ft_strup.c.s

source/string/ft_tolower.o: source/string/ft_tolower.c.o

.PHONY : source/string/ft_tolower.o

# target to build an object file
source/string/ft_tolower.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_tolower.c.o
.PHONY : source/string/ft_tolower.c.o

source/string/ft_tolower.i: source/string/ft_tolower.c.i

.PHONY : source/string/ft_tolower.i

# target to preprocess a source file
source/string/ft_tolower.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_tolower.c.i
.PHONY : source/string/ft_tolower.c.i

source/string/ft_tolower.s: source/string/ft_tolower.c.s

.PHONY : source/string/ft_tolower.s

# target to generate assembly for a file
source/string/ft_tolower.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_tolower.c.s
.PHONY : source/string/ft_tolower.c.s

source/string/ft_toupper.o: source/string/ft_toupper.c.o

.PHONY : source/string/ft_toupper.o

# target to build an object file
source/string/ft_toupper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_toupper.c.o
.PHONY : source/string/ft_toupper.c.o

source/string/ft_toupper.i: source/string/ft_toupper.c.i

.PHONY : source/string/ft_toupper.i

# target to preprocess a source file
source/string/ft_toupper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_toupper.c.i
.PHONY : source/string/ft_toupper.c.i

source/string/ft_toupper.s: source/string/ft_toupper.c.s

.PHONY : source/string/ft_toupper.s

# target to generate assembly for a file
source/string/ft_toupper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/ft_toupper.c.s
.PHONY : source/string/ft_toupper.c.s

source/string/get_next_line.o: source/string/get_next_line.c.o

.PHONY : source/string/get_next_line.o

# target to build an object file
source/string/get_next_line.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/get_next_line.c.o
.PHONY : source/string/get_next_line.c.o

source/string/get_next_line.i: source/string/get_next_line.c.i

.PHONY : source/string/get_next_line.i

# target to preprocess a source file
source/string/get_next_line.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/get_next_line.c.i
.PHONY : source/string/get_next_line.c.i

source/string/get_next_line.s: source/string/get_next_line.c.s

.PHONY : source/string/get_next_line.s

# target to generate assembly for a file
source/string/get_next_line.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/get_next_line.c.s
.PHONY : source/string/get_next_line.c.s

source/string/read_big_file.o: source/string/read_big_file.c.o

.PHONY : source/string/read_big_file.o

# target to build an object file
source/string/read_big_file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/read_big_file.c.o
.PHONY : source/string/read_big_file.c.o

source/string/read_big_file.i: source/string/read_big_file.c.i

.PHONY : source/string/read_big_file.i

# target to preprocess a source file
source/string/read_big_file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/read_big_file.c.i
.PHONY : source/string/read_big_file.c.i

source/string/read_big_file.s: source/string/read_big_file.c.s

.PHONY : source/string/read_big_file.s

# target to generate assembly for a file
source/string/read_big_file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/read_big_file.c.s
.PHONY : source/string/read_big_file.c.s

source/string/read_file.o: source/string/read_file.c.o

.PHONY : source/string/read_file.o

# target to build an object file
source/string/read_file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/read_file.c.o
.PHONY : source/string/read_file.c.o

source/string/read_file.i: source/string/read_file.c.i

.PHONY : source/string/read_file.i

# target to preprocess a source file
source/string/read_file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/read_file.c.i
.PHONY : source/string/read_file.c.i

source/string/read_file.s: source/string/read_file.c.s

.PHONY : source/string/read_file.s

# target to generate assembly for a file
source/string/read_file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/string/read_file.c.s
.PHONY : source/string/read_file.c.s

source/vector/ft_vec_distance.o: source/vector/ft_vec_distance.c.o

.PHONY : source/vector/ft_vec_distance.o

# target to build an object file
source/vector/ft_vec_distance.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_distance.c.o
.PHONY : source/vector/ft_vec_distance.c.o

source/vector/ft_vec_distance.i: source/vector/ft_vec_distance.c.i

.PHONY : source/vector/ft_vec_distance.i

# target to preprocess a source file
source/vector/ft_vec_distance.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_distance.c.i
.PHONY : source/vector/ft_vec_distance.c.i

source/vector/ft_vec_distance.s: source/vector/ft_vec_distance.c.s

.PHONY : source/vector/ft_vec_distance.s

# target to generate assembly for a file
source/vector/ft_vec_distance.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_distance.c.s
.PHONY : source/vector/ft_vec_distance.c.s

source/vector/ft_vec_dot.o: source/vector/ft_vec_dot.c.o

.PHONY : source/vector/ft_vec_dot.o

# target to build an object file
source/vector/ft_vec_dot.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_dot.c.o
.PHONY : source/vector/ft_vec_dot.c.o

source/vector/ft_vec_dot.i: source/vector/ft_vec_dot.c.i

.PHONY : source/vector/ft_vec_dot.i

# target to preprocess a source file
source/vector/ft_vec_dot.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_dot.c.i
.PHONY : source/vector/ft_vec_dot.c.i

source/vector/ft_vec_dot.s: source/vector/ft_vec_dot.c.s

.PHONY : source/vector/ft_vec_dot.s

# target to generate assembly for a file
source/vector/ft_vec_dot.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_dot.c.s
.PHONY : source/vector/ft_vec_dot.c.s

source/vector/ft_vec_init.o: source/vector/ft_vec_init.c.o

.PHONY : source/vector/ft_vec_init.o

# target to build an object file
source/vector/ft_vec_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_init.c.o
.PHONY : source/vector/ft_vec_init.c.o

source/vector/ft_vec_init.i: source/vector/ft_vec_init.c.i

.PHONY : source/vector/ft_vec_init.i

# target to preprocess a source file
source/vector/ft_vec_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_init.c.i
.PHONY : source/vector/ft_vec_init.c.i

source/vector/ft_vec_init.s: source/vector/ft_vec_init.c.s

.PHONY : source/vector/ft_vec_init.s

# target to generate assembly for a file
source/vector/ft_vec_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_init.c.s
.PHONY : source/vector/ft_vec_init.c.s

source/vector/ft_vec_length.o: source/vector/ft_vec_length.c.o

.PHONY : source/vector/ft_vec_length.o

# target to build an object file
source/vector/ft_vec_length.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_length.c.o
.PHONY : source/vector/ft_vec_length.c.o

source/vector/ft_vec_length.i: source/vector/ft_vec_length.c.i

.PHONY : source/vector/ft_vec_length.i

# target to preprocess a source file
source/vector/ft_vec_length.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_length.c.i
.PHONY : source/vector/ft_vec_length.c.i

source/vector/ft_vec_length.s: source/vector/ft_vec_length.c.s

.PHONY : source/vector/ft_vec_length.s

# target to generate assembly for a file
source/vector/ft_vec_length.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_length.c.s
.PHONY : source/vector/ft_vec_length.c.s

source/vector/ft_vec_multiplication.o: source/vector/ft_vec_multiplication.c.o

.PHONY : source/vector/ft_vec_multiplication.o

# target to build an object file
source/vector/ft_vec_multiplication.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_multiplication.c.o
.PHONY : source/vector/ft_vec_multiplication.c.o

source/vector/ft_vec_multiplication.i: source/vector/ft_vec_multiplication.c.i

.PHONY : source/vector/ft_vec_multiplication.i

# target to preprocess a source file
source/vector/ft_vec_multiplication.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_multiplication.c.i
.PHONY : source/vector/ft_vec_multiplication.c.i

source/vector/ft_vec_multiplication.s: source/vector/ft_vec_multiplication.c.s

.PHONY : source/vector/ft_vec_multiplication.s

# target to generate assembly for a file
source/vector/ft_vec_multiplication.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_multiplication.c.s
.PHONY : source/vector/ft_vec_multiplication.c.s

source/vector/ft_vec_multiplication_num.o: source/vector/ft_vec_multiplication_num.c.o

.PHONY : source/vector/ft_vec_multiplication_num.o

# target to build an object file
source/vector/ft_vec_multiplication_num.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_multiplication_num.c.o
.PHONY : source/vector/ft_vec_multiplication_num.c.o

source/vector/ft_vec_multiplication_num.i: source/vector/ft_vec_multiplication_num.c.i

.PHONY : source/vector/ft_vec_multiplication_num.i

# target to preprocess a source file
source/vector/ft_vec_multiplication_num.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_multiplication_num.c.i
.PHONY : source/vector/ft_vec_multiplication_num.c.i

source/vector/ft_vec_multiplication_num.s: source/vector/ft_vec_multiplication_num.c.s

.PHONY : source/vector/ft_vec_multiplication_num.s

# target to generate assembly for a file
source/vector/ft_vec_multiplication_num.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_multiplication_num.c.s
.PHONY : source/vector/ft_vec_multiplication_num.c.s

source/vector/ft_vec_subtract.o: source/vector/ft_vec_subtract.c.o

.PHONY : source/vector/ft_vec_subtract.o

# target to build an object file
source/vector/ft_vec_subtract.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_subtract.c.o
.PHONY : source/vector/ft_vec_subtract.c.o

source/vector/ft_vec_subtract.i: source/vector/ft_vec_subtract.c.i

.PHONY : source/vector/ft_vec_subtract.i

# target to preprocess a source file
source/vector/ft_vec_subtract.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_subtract.c.i
.PHONY : source/vector/ft_vec_subtract.c.i

source/vector/ft_vec_subtract.s: source/vector/ft_vec_subtract.c.s

.PHONY : source/vector/ft_vec_subtract.s

# target to generate assembly for a file
source/vector/ft_vec_subtract.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_subtract.c.s
.PHONY : source/vector/ft_vec_subtract.c.s

source/vector/ft_vec_sum.o: source/vector/ft_vec_sum.c.o

.PHONY : source/vector/ft_vec_sum.o

# target to build an object file
source/vector/ft_vec_sum.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_sum.c.o
.PHONY : source/vector/ft_vec_sum.c.o

source/vector/ft_vec_sum.i: source/vector/ft_vec_sum.c.i

.PHONY : source/vector/ft_vec_sum.i

# target to preprocess a source file
source/vector/ft_vec_sum.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_sum.c.i
.PHONY : source/vector/ft_vec_sum.c.i

source/vector/ft_vec_sum.s: source/vector/ft_vec_sum.c.s

.PHONY : source/vector/ft_vec_sum.s

# target to generate assembly for a file
source/vector/ft_vec_sum.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/source/vector/ft_vec_sum.c.s
.PHONY : source/vector/ft_vec_sum.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ft"
	@echo "... source/error/char_error.o"
	@echo "... source/error/char_error.i"
	@echo "... source/error/char_error.s"
	@echo "... source/error/ft_exit.o"
	@echo "... source/error/ft_exit.i"
	@echo "... source/error/ft_exit.s"
	@echo "... source/error/int_error.o"
	@echo "... source/error/int_error.i"
	@echo "... source/error/int_error.s"
	@echo "... source/error/void_error.o"
	@echo "... source/error/void_error.i"
	@echo "... source/error/void_error.s"
	@echo "... source/io/ft_putchar.o"
	@echo "... source/io/ft_putchar.i"
	@echo "... source/io/ft_putchar.s"
	@echo "... source/io/ft_putchar_fd.o"
	@echo "... source/io/ft_putchar_fd.i"
	@echo "... source/io/ft_putchar_fd.s"
	@echo "... source/io/ft_putendl.o"
	@echo "... source/io/ft_putendl.i"
	@echo "... source/io/ft_putendl.s"
	@echo "... source/io/ft_putendl_fd.o"
	@echo "... source/io/ft_putendl_fd.i"
	@echo "... source/io/ft_putendl_fd.s"
	@echo "... source/io/ft_putnbr.o"
	@echo "... source/io/ft_putnbr.i"
	@echo "... source/io/ft_putnbr.s"
	@echo "... source/io/ft_putnbr_fd.o"
	@echo "... source/io/ft_putnbr_fd.i"
	@echo "... source/io/ft_putnbr_fd.s"
	@echo "... source/io/ft_putstr.o"
	@echo "... source/io/ft_putstr.i"
	@echo "... source/io/ft_putstr.s"
	@echo "... source/io/ft_putstr_fd.o"
	@echo "... source/io/ft_putstr_fd.i"
	@echo "... source/io/ft_putstr_fd.s"
	@echo "... source/io/print_arr_str.o"
	@echo "... source/io/print_arr_str.i"
	@echo "... source/io/print_arr_str.s"
	@echo "... source/io/putchar_color.o"
	@echo "... source/io/putchar_color.i"
	@echo "... source/io/putchar_color.s"
	@echo "... source/io/putstr_color.o"
	@echo "... source/io/putstr_color.i"
	@echo "... source/io/putstr_color.s"
	@echo "... source/memory/ft_bzero.o"
	@echo "... source/memory/ft_bzero.i"
	@echo "... source/memory/ft_bzero.s"
	@echo "... source/memory/ft_destroy_int_arr.o"
	@echo "... source/memory/ft_destroy_int_arr.i"
	@echo "... source/memory/ft_destroy_int_arr.s"
	@echo "... source/memory/ft_destroy_string_arr.o"
	@echo "... source/memory/ft_destroy_string_arr.i"
	@echo "... source/memory/ft_destroy_string_arr.s"
	@echo "... source/memory/ft_memalloc.o"
	@echo "... source/memory/ft_memalloc.i"
	@echo "... source/memory/ft_memalloc.s"
	@echo "... source/memory/ft_memccpy.o"
	@echo "... source/memory/ft_memccpy.i"
	@echo "... source/memory/ft_memccpy.s"
	@echo "... source/memory/ft_memchr.o"
	@echo "... source/memory/ft_memchr.i"
	@echo "... source/memory/ft_memchr.s"
	@echo "... source/memory/ft_memcmp.o"
	@echo "... source/memory/ft_memcmp.i"
	@echo "... source/memory/ft_memcmp.s"
	@echo "... source/memory/ft_memcpy.o"
	@echo "... source/memory/ft_memcpy.i"
	@echo "... source/memory/ft_memcpy.s"
	@echo "... source/memory/ft_memdel.o"
	@echo "... source/memory/ft_memdel.i"
	@echo "... source/memory/ft_memdel.s"
	@echo "... source/memory/ft_memmove.o"
	@echo "... source/memory/ft_memmove.i"
	@echo "... source/memory/ft_memmove.s"
	@echo "... source/memory/ft_memset.o"
	@echo "... source/memory/ft_memset.i"
	@echo "... source/memory/ft_memset.s"
	@echo "... source/memory/ft_realloc.o"
	@echo "... source/memory/ft_realloc.i"
	@echo "... source/memory/ft_realloc.s"
	@echo "... source/memory/ft_safe_malloc.o"
	@echo "... source/memory/ft_safe_malloc.i"
	@echo "... source/memory/ft_safe_malloc.s"
	@echo "... source/sort/my_bubble_sort.o"
	@echo "... source/sort/my_bubble_sort.i"
	@echo "... source/sort/my_bubble_sort.s"
	@echo "... source/sort/my_quick_sort.o"
	@echo "... source/sort/my_quick_sort.i"
	@echo "... source/sort/my_quick_sort.s"
	@echo "... source/string/ft_atof.o"
	@echo "... source/string/ft_atof.i"
	@echo "... source/string/ft_atof.s"
	@echo "... source/string/ft_atoi.o"
	@echo "... source/string/ft_atoi.i"
	@echo "... source/string/ft_atoi.s"
	@echo "... source/string/ft_atoi_base.o"
	@echo "... source/string/ft_atoi_base.i"
	@echo "... source/string/ft_atoi_base.s"
	@echo "... source/string/ft_find_symb_in_str_arr.o"
	@echo "... source/string/ft_find_symb_in_str_arr.i"
	@echo "... source/string/ft_find_symb_in_str_arr.s"
	@echo "... source/string/ft_getnbr.o"
	@echo "... source/string/ft_getnbr.i"
	@echo "... source/string/ft_getnbr.s"
	@echo "... source/string/ft_isalnum.o"
	@echo "... source/string/ft_isalnum.i"
	@echo "... source/string/ft_isalnum.s"
	@echo "... source/string/ft_isalpha.o"
	@echo "... source/string/ft_isalpha.i"
	@echo "... source/string/ft_isalpha.s"
	@echo "... source/string/ft_isascii.o"
	@echo "... source/string/ft_isascii.i"
	@echo "... source/string/ft_isascii.s"
	@echo "... source/string/ft_isdigit.o"
	@echo "... source/string/ft_isdigit.i"
	@echo "... source/string/ft_isdigit.s"
	@echo "... source/string/ft_isnumber.o"
	@echo "... source/string/ft_isnumber.i"
	@echo "... source/string/ft_isnumber.s"
	@echo "... source/string/ft_isprint.o"
	@echo "... source/string/ft_isprint.i"
	@echo "... source/string/ft_isprint.s"
	@echo "... source/string/ft_itoa.o"
	@echo "... source/string/ft_itoa.i"
	@echo "... source/string/ft_itoa.s"
	@echo "... source/string/ft_len_arr.o"
	@echo "... source/string/ft_len_arr.i"
	@echo "... source/string/ft_len_arr.s"
	@echo "... source/string/ft_strcat.o"
	@echo "... source/string/ft_strcat.i"
	@echo "... source/string/ft_strcat.s"
	@echo "... source/string/ft_strchr.o"
	@echo "... source/string/ft_strchr.i"
	@echo "... source/string/ft_strchr.s"
	@echo "... source/string/ft_strchrdup.o"
	@echo "... source/string/ft_strchrdup.i"
	@echo "... source/string/ft_strchrdup.s"
	@echo "... source/string/ft_strcmp.o"
	@echo "... source/string/ft_strcmp.i"
	@echo "... source/string/ft_strcmp.s"
	@echo "... source/string/ft_strcpy.o"
	@echo "... source/string/ft_strcpy.i"
	@echo "... source/string/ft_strcpy.s"
	@echo "... source/string/ft_strdel.o"
	@echo "... source/string/ft_strdel.i"
	@echo "... source/string/ft_strdel.s"
	@echo "... source/string/ft_strdup.o"
	@echo "... source/string/ft_strdup.i"
	@echo "... source/string/ft_strdup.s"
	@echo "... source/string/ft_strequ.o"
	@echo "... source/string/ft_strequ.i"
	@echo "... source/string/ft_strequ.s"
	@echo "... source/string/ft_striter.o"
	@echo "... source/string/ft_striter.i"
	@echo "... source/string/ft_striter.s"
	@echo "... source/string/ft_striteri.o"
	@echo "... source/string/ft_striteri.i"
	@echo "... source/string/ft_striteri.s"
	@echo "... source/string/ft_strjoin.o"
	@echo "... source/string/ft_strjoin.i"
	@echo "... source/string/ft_strjoin.s"
	@echo "... source/string/ft_strjoin_free.o"
	@echo "... source/string/ft_strjoin_free.i"
	@echo "... source/string/ft_strjoin_free.s"
	@echo "... source/string/ft_strlcat.o"
	@echo "... source/string/ft_strlcat.i"
	@echo "... source/string/ft_strlcat.s"
	@echo "... source/string/ft_strlen.o"
	@echo "... source/string/ft_strlen.i"
	@echo "... source/string/ft_strlen.s"
	@echo "... source/string/ft_strlow.o"
	@echo "... source/string/ft_strlow.i"
	@echo "... source/string/ft_strlow.s"
	@echo "... source/string/ft_strmap.o"
	@echo "... source/string/ft_strmap.i"
	@echo "... source/string/ft_strmap.s"
	@echo "... source/string/ft_strmapi.o"
	@echo "... source/string/ft_strmapi.i"
	@echo "... source/string/ft_strmapi.s"
	@echo "... source/string/ft_strncat.o"
	@echo "... source/string/ft_strncat.i"
	@echo "... source/string/ft_strncat.s"
	@echo "... source/string/ft_strncmp.o"
	@echo "... source/string/ft_strncmp.i"
	@echo "... source/string/ft_strncmp.s"
	@echo "... source/string/ft_strncpy.o"
	@echo "... source/string/ft_strncpy.i"
	@echo "... source/string/ft_strncpy.s"
	@echo "... source/string/ft_strnequ.o"
	@echo "... source/string/ft_strnequ.i"
	@echo "... source/string/ft_strnequ.s"
	@echo "... source/string/ft_strnew.o"
	@echo "... source/string/ft_strnew.i"
	@echo "... source/string/ft_strnew.s"
	@echo "... source/string/ft_strnstr.o"
	@echo "... source/string/ft_strnstr.i"
	@echo "... source/string/ft_strnstr.s"
	@echo "... source/string/ft_strrchr.o"
	@echo "... source/string/ft_strrchr.i"
	@echo "... source/string/ft_strrchr.s"
	@echo "... source/string/ft_strrev.o"
	@echo "... source/string/ft_strrev.i"
	@echo "... source/string/ft_strrev.s"
	@echo "... source/string/ft_strsplit.o"
	@echo "... source/string/ft_strsplit.i"
	@echo "... source/string/ft_strsplit.s"
	@echo "... source/string/ft_strstr.o"
	@echo "... source/string/ft_strstr.i"
	@echo "... source/string/ft_strstr.s"
	@echo "... source/string/ft_strsub.o"
	@echo "... source/string/ft_strsub.i"
	@echo "... source/string/ft_strsub.s"
	@echo "... source/string/ft_strtrim.o"
	@echo "... source/string/ft_strtrim.i"
	@echo "... source/string/ft_strtrim.s"
	@echo "... source/string/ft_strup.o"
	@echo "... source/string/ft_strup.i"
	@echo "... source/string/ft_strup.s"
	@echo "... source/string/ft_tolower.o"
	@echo "... source/string/ft_tolower.i"
	@echo "... source/string/ft_tolower.s"
	@echo "... source/string/ft_toupper.o"
	@echo "... source/string/ft_toupper.i"
	@echo "... source/string/ft_toupper.s"
	@echo "... source/string/get_next_line.o"
	@echo "... source/string/get_next_line.i"
	@echo "... source/string/get_next_line.s"
	@echo "... source/string/read_big_file.o"
	@echo "... source/string/read_big_file.i"
	@echo "... source/string/read_big_file.s"
	@echo "... source/string/read_file.o"
	@echo "... source/string/read_file.i"
	@echo "... source/string/read_file.s"
	@echo "... source/vector/ft_vec_distance.o"
	@echo "... source/vector/ft_vec_distance.i"
	@echo "... source/vector/ft_vec_distance.s"
	@echo "... source/vector/ft_vec_dot.o"
	@echo "... source/vector/ft_vec_dot.i"
	@echo "... source/vector/ft_vec_dot.s"
	@echo "... source/vector/ft_vec_init.o"
	@echo "... source/vector/ft_vec_init.i"
	@echo "... source/vector/ft_vec_init.s"
	@echo "... source/vector/ft_vec_length.o"
	@echo "... source/vector/ft_vec_length.i"
	@echo "... source/vector/ft_vec_length.s"
	@echo "... source/vector/ft_vec_multiplication.o"
	@echo "... source/vector/ft_vec_multiplication.i"
	@echo "... source/vector/ft_vec_multiplication.s"
	@echo "... source/vector/ft_vec_multiplication_num.o"
	@echo "... source/vector/ft_vec_multiplication_num.i"
	@echo "... source/vector/ft_vec_multiplication_num.s"
	@echo "... source/vector/ft_vec_subtract.o"
	@echo "... source/vector/ft_vec_subtract.i"
	@echo "... source/vector/ft_vec_subtract.s"
	@echo "... source/vector/ft_vec_sum.o"
	@echo "... source/vector/ft_vec_sum.i"
	@echo "... source/vector/ft_vec_sum.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

